"""
Skev Language - Python Emitter
AST -> Runnable Python Code
Copyright (c) 2026 AJ. All Rights Reserved. skev.dev | skev.org

WHAT IS AN EMITTER?
-------------------
The emitter is the final step of the Skev -> Python transpiler.
It walks the AST produced by the parser and generates Python source
code that can be executed immediately.

Full pipeline:
  Source text -> [LEXER] -> Tokens -> [PARSER] -> AST -> [EMITTER] -> Python code
                                                                            |
                                                                     python3 runs it

WHAT EACH SKEV CONSTRUCT BECOMES:

  entity Player >>         ->  class Player(Entity):
      health :: int = 100  ->      def __init__(self):
      has Physics          ->          self.health = 100
      when update(delta)   ->          self.attach(Physics())
          move()           ->      def on_update(self, delta):
      << update            ->          self.move()
  << Player

  data DamageEvent >>      ->  class DamageEvent(SkevData):
      amount :: float      ->      def __init__(self, amount=0.0):
  << DamageEvent           ->          self.amount = amount

  kind GameState >>        ->  class GameState(Enum):
      menu                 ->      menu    = "menu"
      playing              ->      playing = "playing"
  << GameState

  succeed value            ->  return succeed(value)
  fail ErrorType           ->  return fail(ErrorType)
  result value             ->  return value

SELF-PREFIX RESOLUTION:
------------------------
Inside entity methods, property names need 'self.' prefix in Python.
The emitter collects all property names from an entity's body at the
start of each class, then qualifies any Identifier that matches.

  Skev:   health -= damage        (inside entity method)
  Python: self.health -= damage   (emitter adds self.)

SPEC REFERENCE: Chapter 2, Chapter 3, Chapter 5, Chapter 6
"""

from __future__ import annotations
from typing import List, Optional, Set
from skev_parser import (
    Program, EntityDecl, DataDecl, KindDecl, AliasDecl, ImportDecl,
    PropertyDecl, ComponentDecl, EventHandler, FunctionDecl,
    IfStmt, MatchStmt, MatchArm, LoopStmt, AssignStmt, VarDecl,
    ReturnStmt, AssertStmt, ExprStmt,
    IntLiteral, FloatLiteral, StringLiteral, BoolLiteral, NothingLiteral,
    Identifier, MemberAccess, CallExpr, BinaryExpr, UnaryExpr,
    TypeExpr, IndexExpr, PropagateExpr, ASTNode,
    parse,
)


# Python keywords that need mangling if used as Skev names
_PY_KEYWORDS = {
    'type', 'pass', 'class', 'return', 'lambda', 'yield',
    'with', 'del', 'global', 'nonlocal', 'raise', 'try',
    'except', 'finally', 'async', 'await',
}


def _safe_name(name: str) -> str:
    """
    Ensure a Skev identifier is safe to use as a Python identifier.
    Python reserved words get a trailing underscore.
    """
    if name in _PY_KEYWORDS:
        return name + '_'
    return name


class Emitter:
    """
    Walks the AST and generates Python source code.

    Usage:
        emitter = Emitter(program)
        python_code = emitter.emit()
        exec(python_code)  # runs the Skev program!
    """

    def __init__(self, program: Program):
        self.program = program
        self.lines: List[str] = []
        self._indent: int = 0

        # These track what entity we are currently inside,
        # so we know which identifiers need 'self.' prefix.
        self._entity_props: Set[str] = set()  # all entity member names (props+methods)
        self._local_vars:   Set[str] = set()  # local variables in current function
        self._in_method: bool = False          # inside an entity method/event?

        # Counter for unique match variable names (avoids clashes)
        self._match_counter: int = 0

    # ── Output helpers ─────────────────────────────────────────────

    def _w(self, text: str = "") -> None:
        """Write one line with current indentation."""
        if text:
            self.lines.append("    " * self._indent + text)
        else:
            self.lines.append("")

    def _indent_in(self) -> None:
        """Increase indentation level."""
        self._indent += 1

    def _indent_out(self) -> None:
        """Decrease indentation level."""
        self._indent -= 1

    # ── Main entry point ────────────────────────────────────────────

    def emit(self) -> str:
        """
        Generate complete Python source code from the AST.
        Returns a string of Python code ready to execute.
        """
        # File header - imports the Skev runtime library
        self._w("# Generated by the Skev Python Transpiler")
        self._w("# Copyright (c) 2026 AJ. All Rights Reserved.")
        self._w("# skev.dev | skev.org")
        self._w("from skev_runtime import *")
        self._w("from enum import Enum")
        self._w()

        # Emit each top-level declaration
        for decl in self.program.declarations:
            self._decl(decl)
            self._w()

        return "\n".join(self.lines)

    # ── Top-level declarations ──────────────────────────────────────

    def _decl(self, node: ASTNode) -> None:
        """Dispatch to the right emitter for each declaration type."""
        if isinstance(node, EntityDecl):   self._entity(node)
        elif isinstance(node, DataDecl):   self._data(node)
        elif isinstance(node, KindDecl):   self._kind(node)
        elif isinstance(node, AliasDecl):  self._alias(node)
        elif isinstance(node, ImportDecl): self._import(node)
        elif isinstance(node, FunctionDecl): self._standalone_fn(node)
        else:
            self._w(f"# [UNHANDLED: {type(node).__name__}]")

    # ── Entity ──────────────────────────────────────────────────────

    def _entity(self, node: EntityDecl) -> None:
        """
        Emit a Skev entity as a Python class.

        entity Player >>          ->   class Player(Entity):
            health :: int = 100   ->       def __init__(self):
            has Physics           ->           self.health = 100
        << Player                 ->           self.attach(Physics())
        """
        # Collect ALL entity member names (properties + methods) for self. prefix.
        # Method calls like can_carry(item) need self.can_carry(item) inside methods.
        self._entity_props = set()
        for b in node.body:
            if isinstance(b, PropertyDecl):
                self._entity_props.add(b.name)
            elif isinstance(b, FunctionDecl):
                self._entity_props.add(b.name)
            elif isinstance(b, EventHandler):
                self._entity_props.add(b.event_name)

        self._w(f"class {node.name}(Entity):")
        self._indent_in()

        # Collect the body parts by type
        props  = [b for b in node.body if isinstance(b, PropertyDecl)]
        comps  = [b for b in node.body if isinstance(b, ComponentDecl)]
        events = [b for b in node.body if isinstance(b, EventHandler)]
        fns    = [b for b in node.body if isinstance(b, FunctionDecl)]

        # __init__ — properties + component attachments
        self._w("def __init__(self):")
        self._indent_in()
        self._w("super().__init__()")

        if props:
            for prop in props:
                default = self._default_value(prop)
                self._w(f"self.{_safe_name(prop.name)} = {default}")
        if comps:
            for comp in comps:
                self._w(f"self.attach({comp.component_name}())")
        if not props and not comps:
            self._w("pass")

        self._indent_out()

        # Event handlers -> on_eventname() methods
        for event in events:
            self._w()
            self._event_handler(event)

        # Functions -> regular methods
        for fn in fns:
            self._w()
            self._method(fn)

        # Empty class guard (shouldn't happen but safety net)
        if not props and not comps and not events and not fns:
            self._w("    pass")

        self._indent_out()

        # Clear entity scope when done
        self._entity_props = set()

    def _default_value(self, prop: PropertyDecl) -> str:
        """Get the default value string for a property."""
        if prop.value is not None:
            return self._expr(prop.value)
        # No default given — use a sensible type default
        if prop.type_expr:
            return self._type_default(prop.type_expr)
        return "None"

    def _type_default(self, type_expr: Optional[TypeExpr]) -> str:
        """Return a sensible Python default value for a Skev type."""
        if type_expr is None:
            return "None"
        name = type_expr.name.lower()
        if name in ("int", "uint8", "uint16", "uint32", "uint64",
                    "int8", "int16", "int32", "int64"):
            return "0"
        if name in ("float", "float32", "float64"):
            return "0.0"
        if name == "bool":
            return "False"
        if name == "string":
            return '""'
        if name in ("maybe", "weak"):
            return "nothing()"
        if name in ("list",):
            return "[]"
        if name in ("map",):
            return "{}"
        if name == "nothing":
            return "None"
        return "None"

    def _event_handler(self, node: EventHandler) -> None:
        """
        Emit an event handler as a Python method.

        Skev:                           Python:
        when update(delta)          ->  def on_update(self, delta):
            health -= damage        ->      self.health -= damage
        << update
        """
        # Build parameter list
        params = self._param_str(node.params)
        method_name = f"on_{node.event_name}"

        self._w(f"def {method_name}(self{params}):")
        self._indent_in()
        self._in_method = True
        # Build local scope: params + var decls (prevents wrongful self. prefix)
        self._local_vars = {p[0] for p in node.params}
        self._local_vars |= self._collect_local_vars(node.body)

        if node.body:
            for stmt in node.body:
                self._stmt(stmt)
        else:
            self._w("pass")

        self._in_method = False
        self._local_vars = set()
        self._indent_out()

    def _method(self, node: FunctionDecl) -> None:
        """
        Emit a function declaration inside an entity as a Python method.

        Skev:                                   Python:
        take_damage(amount: int) -> nothing ->  def take_damage(self, amount):
            health -= amount                ->      self.health -= amount
        << take_damage
        """
        params = self._param_str(node.params)
        self._w(f"def {_safe_name(node.name)}(self{params}):")
        self._indent_in()
        self._in_method = True
        self._local_vars = {p[0] for p in node.params}
        self._local_vars |= self._collect_local_vars(node.body)

        if node.body:
            for stmt in node.body:
                self._stmt(stmt)
        else:
            self._w("pass")

        self._in_method = False
        self._local_vars = set()
        self._indent_out()

    def _standalone_fn(self, node: FunctionDecl) -> None:
        """
        Emit a standalone function (not inside an entity).

        Skev:                          Python:
        identity(value: int) -> int -> def identity(value):
            result value           ->     return value
        << identity
        """
        params = self._param_str(node.params, include_comma=False)
        self._w(f"def {_safe_name(node.name)}({params}):")
        self._indent_in()
        self._in_method = False

        if node.body:
            for stmt in node.body:
                self._stmt(stmt)
        else:
            self._w("pass")

        self._indent_out()

    # ── Data type ───────────────────────────────────────────────────

    def _data(self, node: DataDecl) -> None:
        """
        Emit a Skev data type as a Python class.

        Skev:                            Python:
        data DamageEvent >>          ->  class DamageEvent(SkevData):
            amount :: float          ->      def __init__(self, amount=0.0):
            critical :: bool = false ->          self.amount = amount
        << DamageEvent               ->          self.critical = False
        """
        self._w(f"class {node.name}(SkevData):")
        self._indent_in()

        props = [b for b in node.body if isinstance(b, PropertyDecl)]

        # __init__ with all fields as parameters
        param_parts = []
        for prop in props:
            default = self._default_value(prop)
            param_parts.append(f"{_safe_name(prop.name)}={default}")

        param_str = ", ".join(param_parts)
        if param_str:
            self._w(f"def __init__(self, {param_str}):")
        else:
            self._w("def __init__(self):")

        self._indent_in()
        if props:
            for prop in props:
                self._w(f"self.{_safe_name(prop.name)} = {_safe_name(prop.name)}")
        else:
            self._w("pass")
        self._indent_out()

        if not props:
            self._w("pass")

        self._indent_out()

    # ── Kind (enum) ─────────────────────────────────────────────────

    def _kind(self, node: KindDecl) -> None:
        """
        Emit a Skev kind as a Python Enum.

        Skev:                    Python:
        kind GameState >>    ->  class GameState(Enum):
            menu             ->      menu    = "menu"
            playing          ->      playing = "playing"
        << GameState
        """
        self._w(f"class {node.name}(Enum):")
        self._indent_in()

        if node.variants:
            for variant in node.variants:
                self._w(f'{variant} = "{variant}"')
        else:
            self._w("pass")

        self._indent_out()

    # ── Alias ───────────────────────────────────────────────────────

    def _alias(self, node: AliasDecl) -> None:
        """
        Emit a Skev alias as a Python comment.
        Python type aliases don't affect runtime behaviour.

        Skev:  alias EntityID = uint32
        Python: EntityID = int  # alias: uint32
        """
        # Map to Python type or just use as comment
        target = node.target.strip()
        py_type = self._map_type_str(target)
        self._w(f"{node.name} = {py_type}  # alias: {target}")

    def _map_type_str(self, type_str: str) -> str:
        """Map a Skev type string to a Python equivalent."""
        mapping = {
            "int": "int", "uint32": "int", "uint64": "int",
            "int32": "int", "int64": "int", "uint8": "int",
            "float": "float", "float32": "float", "float64": "float",
            "bool": "bool", "string": "str", "nothing": "type(None)",
        }
        return mapping.get(type_str, type_str)

    # ── Import ──────────────────────────────────────────────────────

    def _import(self, node: ImportDecl) -> None:
        """
        Emit a Skev import as a Python comment.
        The Skev runtime already provides all standard library modules.

        Skev:  import skev.math
        Python: # import skev.math (available via skev_runtime)
        """
        self._w(f"# import {node.path}  (available via skev_runtime)")

    # ── Statements ──────────────────────────────────────────────────

    def _stmt(self, node: ASTNode) -> None:
        """Dispatch to the right statement emitter."""
        if isinstance(node, IfStmt):      self._if_stmt(node)
        elif isinstance(node, MatchStmt): self._match_stmt(node)
        elif isinstance(node, LoopStmt):  self._loop_stmt(node)
        elif isinstance(node, AssignStmt): self._assign_stmt(node)
        elif isinstance(node, VarDecl):   self._var_decl(node)
        elif isinstance(node, ReturnStmt): self._return_stmt(node)
        elif isinstance(node, AssertStmt): self._assert_stmt(node)
        elif isinstance(node, ExprStmt):  self._expr_stmt(node)
        else:
            self._w(f"# [UNHANDLED STMT: {type(node).__name__}]")

    def _if_stmt(self, node: IfStmt) -> None:
        """
        Skev:                    Python:
        if health < 0 >>     ->  if self.health < 0:
            die()            ->      self.die()
        << health < 0
        else >>              ->  else:
            respawn()        ->      self.respawn()
        << else
        """
        cond = self._expr(node.condition)
        self._w(f"if {cond}:")
        self._indent_in()
        if node.then_body:
            for s in node.then_body:
                self._stmt(s)
        else:
            self._w("pass")
        self._indent_out()

        if node.else_body:
            self._w("else:")
            self._indent_in()
            for s in node.else_body:
                self._stmt(s)
            self._indent_out()

    def _match_stmt(self, node: MatchStmt) -> None:
        """
        Emit a match statement as a Python if/elif chain.

        Skev:                          Python:
        match state >>             ->  _m0 = self.state
            menu    -> show_menu() ->  if _m0 == GameState.menu:
            playing -> run_game()  ->      self.show_menu()
        << state                   ->  elif _m0 == GameState.playing:
                                   ->      self.run_game()

        We use a temp variable _mN to avoid evaluating the match
        expression multiple times.
        """
        self._match_counter += 1
        temp = f"_m{self._match_counter}"
        val = self._expr(node.value)
        self._w(f"{temp} = {val}")

        for i, arm in enumerate(node.arms):
            pat = self._match_pattern(arm.pattern)
            keyword = "if" if i == 0 else "elif"

            # Wildcard arm: _ -> default
            if isinstance(arm.pattern, Identifier) and arm.pattern.name == "_":
                self._w("else:")
            else:
                self._w(f"{keyword} {temp} == {pat}:")

            self._indent_in()
            if arm.body:
                for s in arm.body:
                    self._stmt(s)
            else:
                self._w("pass")
            self._indent_out()

    def _match_pattern(self, node: ASTNode) -> str:
        """
        Emit a match arm pattern.
        For enum variants: try to qualify with the enum class name.
        For literals: emit as-is.
        """
        if isinstance(node, Identifier):
            # Wildcard
            if node.name == "_":
                return "_"
            # Otherwise emit as identifier — qualified if needed
            return node.name
        return self._expr(node)

    def _loop_stmt(self, node: LoopStmt) -> None:
        """
        Three loop forms:

        iterate: loop item in enemies >>   ->  for item in self.enemies:
        range:   loop i from 0 to 10 >>   ->  for i in range(0, 10):
        while:   loop while alive >>       ->  while self.alive:
        """
        if node.kind == "iterate":
            it = self._expr(node.iterable)
            self._w(f"for {node.var_name} in {it}:")

        elif node.kind == "range":
            fr = self._expr(node.from_expr)
            to = self._expr(node.to_expr)
            self._w(f"for {node.var_name} in range({fr}, {to}):")

        elif node.kind == "while":
            cond = self._expr(node.condition)
            self._w(f"while {cond}:")

        self._indent_in()
        if node.body:
            for s in node.body:
                self._stmt(s)
        else:
            self._w("pass")
        self._indent_out()

    def _assign_stmt(self, node: AssignStmt) -> None:
        """
        Skev:  health -= damage       Python: self.health -= damage
        Skev:  score = 0              Python: score = 0
        """
        target = self._expr(node.target)
        value  = self._expr(node.value)
        self._w(f"{target} {node.operator} {value}")

    def _var_decl(self, node: VarDecl) -> None:
        """
        Local variable declaration.

        Skev:  damage :: int = 50     Python: damage = 50
        Skev:  name :: string         Python: name = ""
        """
        name = _safe_name(node.name)
        if node.value is not None:
            value = self._expr(node.value)
        else:
            value = self._type_default(node.type_expr)
        self._w(f"{name} = {value}")

    def _return_stmt(self, node: ReturnStmt) -> None:
        """
        Skev:  result value     Python: return value
        Skev:  succeed value    Python: return succeed(value)
        Skev:  fail ErrorType   Python: return fail(ErrorType)
        """
        if node.kind == "result":
            if node.value:
                self._w(f"return {self._expr(node.value)}")
            else:
                self._w("return None")

        elif node.kind == "succeed":
            if node.value:
                self._w(f"return succeed({self._expr(node.value)})")
            else:
                self._w("return succeed(None)")

        elif node.kind == "fail":
            if node.value:
                self._w(f"return fail({self._expr(node.value)})")
            else:
                self._w("return fail(None)")

    def _assert_stmt(self, node: AssertStmt) -> None:
        """
        Skev:  assert health >= 0 "Health cannot be negative"
        Python: skev_assert(self.health >= 0, "Health cannot be negative")
        """
        cond = self._expr(node.condition)
        if node.message:
            self._w(f'skev_assert({cond}, "{node.message}")')
        else:
            self._w(f"skev_assert({cond})")

    def _expr_stmt(self, node: ExprStmt) -> None:
        """
        An expression used as a statement (usually a function call).

        Skev:  audio.play(sounds.explosion)
        Python: self.audio.play(sounds.explosion)  [if audio is a property]
        """
        if isinstance(node.expr, Identifier) and node.expr.name == "stop":
            self._w("break")
        elif isinstance(node.expr, Identifier) and node.expr.name == "skip":
            self._w("continue")
        elif isinstance(node.expr, PropagateExpr):
            # -> operation() — just run it, propagation simplified
            inner = self._expr(node.expr.expr)
            self._w(f"{inner}.propagate()")
        else:
            self._w(self._expr(node.expr))

    # ── Expressions ─────────────────────────────────────────────────

    def _expr(self, node: Optional[ASTNode]) -> str:
        """
        Convert an AST expression node to a Python expression string.
        This is the core of the emitter — every expression type handled here.
        """
        if node is None:
            return "None"

        if isinstance(node, IntLiteral):
            return str(node.value)

        if isinstance(node, FloatLiteral):
            # Ensure floats always have a decimal point
            s = repr(node.value)
            return s

        if isinstance(node, StringLiteral):
            # Re-quote the string. Handle Skev {interpolation} -> Python f-strings
            raw = node.value
            if "{" in raw and "{{" not in raw:
                # Has interpolation — convert to f-string
                return f'f"{raw}"'
            else:
                # Literal braces: {{ -> {
                raw = raw.replace("{{", "{").replace("}}", "}")
                return f'"{raw}"'

        if isinstance(node, BoolLiteral):
            # Skev: true/false -> Python: True/False
            return "True" if node.value else "False"

        if isinstance(node, NothingLiteral):
            # Skev: nothing -> Python: nothing() from runtime
            return "nothing()"

        if isinstance(node, Identifier):
            name = node.name
            # Resolve game-native type constructors
            if name.endswith("!"):
                return name[:-1]  # Vector3! -> Vector3 (class from runtime)
            # Inside an entity method, entity properties get self. prefix
            if (self._in_method and name in self._entity_props
                    and name not in self._local_vars):
                return f"self.{_safe_name(name)}"
            return _safe_name(name)

        if isinstance(node, MemberAccess):
            obj = self._expr(node.obj)
            return f"{obj}.{_safe_name(node.member)}"

        if isinstance(node, CallExpr):
            callee = self._expr(node.callee)
            args = ", ".join(self._expr(a) for a in node.args)
            return f"{callee}({args})"

        if isinstance(node, BinaryExpr):
            left  = self._expr(node.left)
            right = self._expr(node.right)
            op = self._map_operator(node.operator)
            return f"({left} {op} {right})"

        if isinstance(node, UnaryExpr):
            op      = self._map_operator(node.operator)
            operand = self._expr(node.operand)
            return f"({op}{operand})"

        if isinstance(node, IndexExpr):
            obj   = self._expr(node.obj)
            index = self._expr(node.index)
            return f"{obj}[{index}]"

        if isinstance(node, PropagateExpr):
            # -> expr — emit as expr.propagate() for result types
            inner = self._expr(node.expr)
            return f"{inner}.propagate()"

        if isinstance(node, TypeExpr):
            # Type used as expression (e.g. in result[T] context)
            return node.name

        return f"# [UNHANDLED EXPR: {type(node).__name__}]"

    def _map_operator(self, op: str) -> str:
        """
        Map Skev operators to Python operators.
        Most are identical. Some need translation.
        """
        mapping = {
            "and": "and",
            "or":  "or",
            "not": "not ",    # trailing space: not(x) -> not x
            "is":  "==",      # Skev 'is' for type check simplified to ==
        }
        return mapping.get(op, op)

    # ── Helpers ──────────────────────────────────────────────────────

    def _param_str(self, params: list, include_comma: bool = True) -> str:
        """
        Build a parameter string for a Python function definition.

        params: list of (name, type_str, default) tuples
        include_comma: if True, prefix with ', ' (for methods after 'self')
        """
        if not params:
            return ""
        parts = []
        for name, type_str, default in params:
            if default is not None:
                parts.append(f"{_safe_name(name)}={self._expr(default)}")
            else:
                parts.append(_safe_name(name))
        param_str = ", ".join(parts)
        if include_comma:
            return f", {param_str}"
        return param_str

    def _collect_local_vars(self, stmts) -> Set[str]:
        """
        Recursively collect all local variable names from a function body.
        This prevents local variables from getting self. prefix when they
        happen to share a name with an entity method or property.
        """
        from skev_parser import VarDecl, IfStmt, LoopStmt, MatchStmt
        names = set()
        for stmt in stmts:
            if isinstance(stmt, VarDecl):
                names.add(stmt.name)
            elif isinstance(stmt, IfStmt):
                names |= self._collect_local_vars(stmt.then_body)
                names |= self._collect_local_vars(stmt.else_body)
            elif isinstance(stmt, LoopStmt):
                if stmt.var_name:
                    names.add(stmt.var_name)  # loop variable
                names |= self._collect_local_vars(stmt.body)
            elif isinstance(stmt, MatchStmt):
                for arm in stmt.arms:
                    names |= self._collect_local_vars(arm.body)
        return names


# =============================================================
# CONVENIENCE FUNCTION
# =============================================================

def emit(source: str, filename: str = "<source>") -> tuple:
    """
    Transpile Skev source code to Python source code.

    Args:
        source:   complete Skev source code
        filename: for error messages (optional)

    Returns:
        (python_code, errors)
        python_code: Python source code string (ready to exec or run)
        errors:      list of parse/lex errors (empty if source is valid)

    Example:
        code, errors = emit('entity Player >> health :: int = 100 << Player')
        if not errors:
            exec(code)              # runs the code
            p = Player()            # creates a Player instance
            print(p.health)         # prints 100
    """
    program, errors = parse(source, filename)
    if errors:
        return "", errors
    emitter = Emitter(program)
    python_code = emitter.emit()
    return python_code, []
